export function getMockProducts() {
  return [
    {
      _id: 'demo-rolex',
      title: 'Rolex Daytona 116500LN',
      description: 'Ceas sport din oțel, cadran alb, ceramică neagră.',
      images: ['https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1600&auto=format&fit=crop'],
      locales: [
        { locale: 'ro', title: 'Rolex Daytona 116500LN', description: 'Ceas sport din oțel, cadran alb, ceramică neagră.' },
        { locale: 'en', title: 'Rolex Daytona 116500LN', description: 'Steel sport watch, white dial, black ceramic.' },
        { locale: 'it', title: 'Rolex Daytona 116500LN', description: 'Orologio sportivo in acciaio, quadrante bianco, ceramica nera.' },
      ],
      auction_start_price: 15000,
      buy_now_price: 27500,
      shares_total: 100,
      share_price: 300,
      raffle_tickets_total: 1000,
      raffle_ticket_price: 25,
      status: 'in_voting',
      counts: { auction: 24, buy_now: 18, tokenization: 42, raffle: 10, not_interested: 6 },
    },
    {
      _id: 'demo-ferrari',
      title: 'Ferrari F8 Tributo',
      description: 'Supercar V8 twin-turbo, roșu corsa.',
      images: ['https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1600&auto=format&fit=crop'],
      locales: [
        { locale: 'ro', title: 'Ferrari F8 Tributo', description: 'Supercar V8 twin-turbo, roșu corsa.' },
        { locale: 'en', title: 'Ferrari F8 Tributo', description: 'V8 twin‑turbo supercar, Rosso Corsa.' },
        { locale: 'it', title: 'Ferrari F8 Tributo', description: 'Supercar V8 biturbo, Rosso Corsa.' },
      ],
      auction_start_price: 220000,
      buy_now_price: 320000,
      shares_total: 1000,
      share_price: 500,
      raffle_tickets_total: 5000,
      raffle_ticket_price: 50,
      status: 'in_voting',
      counts: { auction: 55, buy_now: 12, tokenization: 20, raffle: 8, not_interested: 5 },
    },
    {
      _id: 'demo-villa',
      title: 'Vila pe malul lacului',
      description: 'Proprietate exclusivă cu ponton privat.',
      images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1600&auto=format&fit=crop'],
      locales: [
        { locale: 'ro', title: 'Vila pe malul lacului', description: 'Proprietate exclusivă cu ponton privat.' },
        { locale: 'en', title: 'Lakefront Villa', description: 'Exclusive property with private dock.' },
        { locale: 'it', title: 'Villa sul lago', description: 'Proprietà esclusiva con molo privato.' },
      ],
      auction_start_price: 450000,
      buy_now_price: 650000,
      shares_total: 10000,
      share_price: 1500,
      raffle_tickets_total: 20000,
      raffle_ticket_price: 200,
      status: 'in_voting',
      counts: { auction: 35, buy_now: 25, tokenization: 22, raffle: 12, not_interested: 6 },
    },
  ]
}
